"""
DocsVerse AI - Professional Python PDF Generator using ReportLab
Generates publication-quality PDF documents with executive layouts,
themed color schemes, and mandatory Amar Smart India branding.
"""

import sys
import os
import json
import tempfile
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether, ListFlowable, ListItem
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and print total page count
    and enforce DocVerse AI branding in the footer.
    """
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super(NumberedCanvas, self).showPage()
        super(NumberedCanvas, self).save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        width, height = letter

        # Running Header (pages after page 1)
        if self._pageNumber > 1:
            self.drawString(54, height - 36, "DocsVerse AI — Intelligence Report")
            self.setStrokeColor(colors.HexColor("#e2e8f0"))
            self.setLineWidth(0.5)
            self.line(54, height - 42, width - 54, height - 42)

        # Running Footer (all pages)
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.75)
        self.line(54, 45, width - 54, 45)

        # Mandatory Footer Branding
        footer_brand = "Generated by DocVerse AI (Amar Smart India)"
        self.drawString(54, 30, footer_brand)

        # Page Number Indicator
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(width - 54, 30, page_str)

        self.restoreState()


def clean_html_tags(text):
    """Clean markdown artifacts for ReportLab Paragraph safety."""
    if not text:
        return ""
    # ReportLab Paragraph supports simple <b>, <i>, <font>, <u>
    # Replace markdown bold and italic
    import re
    # Bold **text** -> <b>text</b>
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    # Italic *text* -> <i>\1</i>
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
    # Replace markdown headings markers if inside paragraph
    text = re.sub(r'^#+\s*', '', text)
    # Escape standalone & characters that aren't xml entities
    text = re.sub(r'&(?!(amp|lt|gt|quot|apos);)', '&amp;', text)
    return text


def build_pdf(data, output_filepath):
    """Build the styled PDF file from structured payload."""
    doc = SimpleDocTemplate(
        output_filepath,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocVerseTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        'DocVerseSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=14
    )

    meta_style = ParagraphStyle(
        'DocVerseMeta',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor('#4f46e5')
    )

    h1_style = ParagraphStyle(
        'DocVerseH1',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=17,
        textColor=colors.HexColor('#1e1b4b'),
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        'DocVerseBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=14.5,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )

    bullet_style = ParagraphStyle(
        'DocVerseBullet',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor('#334155'),
        leftIndent=14,
        firstLineIndent=-10,
        spaceAfter=4
    )

    story = []

    # 1. Header Card Banner
    doc_title = data.get('title') or "DocVerse Intelligence Report"
    doc_subtitle = data.get('subtitle') or "Executive Summary & AI Reasoning Analysis"
    timestamp = data.get('date') or datetime.now().strftime("%B %d, %Y • %I:%M %p")
    source_name = data.get('source') or "Interactive Workspace Session"

    # Meta Table Header
    meta_info = f"<b>MODEL:</b> DocVerse AK-1.3 &nbsp;|&nbsp; <b>SOURCE:</b> {clean_html_tags(source_name)} &nbsp;|&nbsp; <b>DATE:</b> {timestamp}"
    meta_p = Paragraph(meta_info, meta_style)

    header_table_data = [
        [Paragraph(clean_html_tags(doc_title), title_style)],
        [Paragraph(clean_html_tags(doc_subtitle), subtitle_style)],
        [meta_p]
    ]

    header_table = Table(header_table_data, colWidths=[letter[0] - 108])
    header_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
        ('LEFTPADDING', (0, 0), (-1, -1), 16),
        ('RIGHTPADDING', (0, 0), (-1, -1), 16),
        ('TOPPADDING', (0, 0), (-1, 0), 14),
        ('BOTTOMPADDING', (0, -1), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 8),
    ]))

    story.append(header_table)
    story.append(Spacer(1, 14))

    # 2. Render Structured Sections
    sections = data.get('sections', [])
    if not sections and data.get('rawText'):
        # Parse raw text into basic sections if needed
        raw_lines = data['rawText'].split('\n')
        current_sec = {'heading': 'Summary & Analysis', 'paragraphs': [], 'bullets': []}
        sections = [current_sec]

        for line in raw_lines:
            s_line = line.strip()
            if not s_line:
                continue
            if s_line.startswith('#'):
                heading_text = s_line.lstrip('#').strip()
                current_sec = {'heading': heading_text, 'paragraphs': [], 'bullets': []}
                sections.append(current_sec)
            elif s_line.startswith(('-', '*', '•')) or (len(s_line) > 2 and s_line[0].isdigit() and s_line[1] in ('.', ')')):
                bullet_text = s_line.lstrip('-*•0123456789.) ').strip()
                current_sec['bullets'].append(bullet_text)
            else:
                current_sec['paragraphs'].append(s_line)

    for idx, sec in enumerate(sections):
        heading = sec.get('heading')
        if heading:
            # Styled section header with a colored accent indicator
            heading_html = f"<font color='#4f46e5'>■</font>&nbsp; {clean_html_tags(heading)}"
            story.append(Paragraph(heading_html, h1_style))
            story.append(HRFlowable(width="100%", thickness=0.8, color=colors.HexColor('#e2e8f0'), spaceAfter=8, spaceBefore=2))

        # Paragraphs in this section
        for para in sec.get('paragraphs', []):
            if para.strip():
                story.append(Paragraph(clean_html_tags(para.strip()), body_style))

        # Bullets in this section
        for b in sec.get('bullets', []):
            if b.strip():
                bullet_html = f"<font color='#6366f1'>●</font>&nbsp;&nbsp;{clean_html_tags(b.strip())}"
                story.append(Paragraph(bullet_html, bullet_style))

        story.append(Spacer(1, 10))

    # Build document
    doc.build(story, canvasmaker=NumberedCanvas)
    return output_filepath


def main():
    if len(sys.argv) < 3:
        print("Usage: python pdf_generator.py <input_json_path> <output_pdf_path>")
        sys.exit(1)

    input_json_path = sys.argv[1]
    output_pdf_path = sys.argv[2]

    try:
        with open(input_json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        build_pdf(data, output_pdf_path)
        print(f"SUCCESS:{output_pdf_path}")
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        print(f"ERROR:{str(e)}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
